### ISSUE TITLE
Usage Question

### ISSUE THREAD

**Issue by DadTheTester** [blazeeboy/dirtree#12]
I tried the command dirtree -o output.html **/* * as you listed it.  Worked fine.

However, I was hoping for just a subdirectory and its tree.  I tried dirtree -o output.html /tor-browser/**/* * and other permutations of that.  It always seems to get all the way to the root of the user directory, but misses the lower levels.

I think I've forgotten my command line usage when it comes to this sort of thing.

Could you please point me in the right direction?

Thanks.

**Comment by emad-elsaid** [comment]
Should be something like : dirtree -o output.html subdir/**/*

**Comment by DadTheTester** [comment]
Is subdir an actual command?

**Comment by DadTheTester** [comment]
/usr/local/bin/dirtree

# To get autocompletion functionality
# run: dirtree completion >> ~/.bashrc
# Or, dirtree completion > /usr/local/etc/bash_completion.d/dirtree
#!/usr/bin/env bash

_dirtree_completions()
{
    local cur prev

    cur=${COMP_WORDS[COMP_CWORD]}
    prev="${COMP_WORDS[COMP_CWORD-1]}"
    COMPREPLY=() 
    if [ "${#COMP_WORDS[@]}" != "2" ]; then
        return
    fi
    case "$cur" in
        -*)
        COMPREPLY=( $( compgen -W '-v -h -l -s -o -t \
                               --version --help --local \
                               --screenshot --output --template' -- $cur ) )                           
        ;;
    esac

    if [[ ${prev} == -t ]] || [[ ${prev} == --template ]]; then
        COMPREPLY=( $( compgen -W 'circles flame tree treemap' -- $cur ) )
    fi

    return 0
}

complete -F _dirtree_completions dirtree

**Comment by emad-elsaid** [comment]
sounds about right, ok when you say it doesn't work what do you exactly mean?

**Comment by emad-elsaid** [comment]
ok we started to mix both issues. I'll close this one
